# syntax = docker/dockerfile:1

FROM node:20-alpine AS base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json package-lock.json ./
RUN npm ci --prefer-offline --no-audit

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]