# Use a Node.js image as the base
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Nuxt application
RUN npm run build

# Stage 2: Production image
FROM node:20-alpine

WORKDIR /app

# Copy only the necessary files for production
# <CHANGED HERE>
COPY --from=builder /app/.output .

# Expose the port Nuxt runs on (default is 3000)
EXPOSE 3000

# Start the Nuxt application in production mode
# <AND HERE>
CMD ["node", "server/index.mjs"]